# Generated by Django 3.0.4 on 2020-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('app_name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=203)),
                ('downloads', models.CharField(max_length=30)),
                ('reviews', models.CharField(max_length=30)),
                ('ratings', models.CharField(max_length=20)),
            ],
        ),
    ]
