# Generated by Django 3.0.4 on 2020-03-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='url',
            field=models.CharField(default='No URL', max_length=200),
            preserve_default=False,
        ),
    ]
