# Generated by Django 3.0.4 on 2020-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_keyword_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='rec_keyword',
            field=models.CharField(default='No Value', max_length=1000),
            preserve_default=False,
        ),
    ]
